name: myapp
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

dependencies:
  args: ^2.3.0
  dart_appwrite: 12.1.0
  equatable: ^2.0.7
  html: ^0.15.4
  http: ^0.13.0
  image_size_getter: ^2.4.0
  image_size_getter_http_input: ^2.0.0
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  lints: ^2.0.0
  test: ^1.21.0
