name: Daily Crawl Trending Meme Worker

on:
  schedule:
    - cron: "0 0 */2 * *" # Runs every 3 days at midnight UTC
  push:
    branches:
      - master

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"

      - name: Install dependencies
        run: dart pub get

      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Run crawler
        run: dart run bin/top_trending_meme_template_crawler.dart
        env:
          APPWRITE_PROJECT_ID: ${{ secrets.APPWRITE_PROJECT_ID }}
          APPWRITE_KEY: ${{ secrets.APPWRITE_KEY }}

      - name: Init git config
        run: git config user.name "dungngminh" && git config user.email "63831488+dungngminh@users.noreply.github.com"

      - name: Add new line to changelog is date crawled
        run: echo -e "## Crawling $(date +'%d-%m-%Y') \n  - ✅ Done" >> CHANGELOG.md

      - name: Pull new code
        run: git pull

      - name: Commit changes
        run: git add . && git commit -m "Crawl $(date +'%Y-%m-%d') done" && git push
